name: MySQL Compose with SQL File

on:
  workflow_dispatch:

jobs:
  mysql-query:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start MySQL with Docker Compose
      run: |
        docker compose -f database/docker-compose.yml up -d
        echo "Waiting for MySQL to be ready..."
        for i in {1..30}; do
          if docker exec mysql-server mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" -e "SELECT 1;" > /dev/null 2>&1; then
            echo "MySQL is ready!"
            break
          fi
          sleep 2
        done


    - name: Stop Docker Compose
      if: always()
      run: docker compose -f database/docker-compose.yml down

