name: Frontend Dev Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build website
        run: pnpm run build

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/
            .next/
            build/
